# NumPy

As a fundamental package for scientific computing, NumPy provides the foundations of mathematical, scientific, engineering and data science programming within the Python Echo-system. NumPy’s main object is the homogeneous multidimensional array.<br>

Almost all of the [PyData](https://pydata.org) Eco-System libraries rely on [NumPy](http://www.numpy.org). This is one of their **most important and main building block**.<br>

Worth reading:
[NumPy's arrays vs Python lists](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

In [2]:
# It's a convention to import NumPy as np for easier reference
import numpy as np

# NumPy Arrays

## Creating NumPy arrays from mutables

To create a NumPy array, from a Python data structure, we use NumPy's array function. 
The NumPy's array function can be accessed by typing `np.array`. 
We need to cast our Python data structure, `my_list`, as a parameter to the array function.

In [3]:
# Create a Python list. 
my_list = [-1,0,1]
my_list, type(my_list)

([-1, 0, 1], list)

In [4]:
# Create a NumPy array
my_array = np.array(my_list) 
my_array, type(my_array)

(array([-1,  0,  1]), numpy.ndarray)

In [5]:
# Likewise we can create 2-D arrays
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
matrix_one = np.array(my_matrix)
matrix_one

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
# We can use Tuple instead of list as well. 
my_tuple = (-1,0,1)
my_array = np.array(my_tuple) 
my_array, type(my_array)

(array([-1,  0,  1]), numpy.ndarray)

## Array creation using NumPy's Built-in methods

Most of the time, we use NumPy built-in methods to create arrays - as they are simpler and faster.

### `arange()`

* `arange()` is very much similar to Python function `range()`. <br>
* Syntax: `arange(start, stop, step, dtype=None)`. <br>
* Return values within a given interval. <br>

In [8]:
# similar to range() in Python, not including 10
np.arange(0,10) 
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# We can give the step
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
# We can give the step and data type
np.arange(0,10,2, dtype=float)

array([0., 2., 4., 6., 8.])

### `linspace()`

Return evenly spaced numbers over a specified interval.<br>

In [11]:
# start from 3 & end at 9 with 6 evenly spaced points b/w 3 to 9.
np.linspace(3, 9, 6)

array([3. , 4.2, 5.4, 6.6, 7.8, 9. ])

In [12]:
# Lets find the step size with "retstep" which returns a tuple of the array and the step size
my_linspace = np.linspace(5, 15, 9, retstep=True)
my_linspace
# my_linspace[1] to get the stepsize only

(array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ]), 1.25)

## Don't Confuse!
  * <b>`arange()` takes 3rd argument as step size.<b><br>
  * <b>`linspace()` take 3rd argument as no of point we want.<b>

### `zeros()`

Returns an array of given size with **all zeros**.<br>

In [13]:
# 1-D array
np.zeros(3)

array([0., 0., 0.])

In [15]:
# 2-D array, by passing a tuple
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### `ones()`

Returns an array of given size with **all ones**.<br>

In [17]:
# 1-D array
np.ones(3)

array([1., 1., 1.])

In [18]:
# 2-D array, by passing a tuple
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### `eye()` 
Creates an identity matrix must be a square matrix, which is useful in several linear algebra problems.
* Return a 2-D array with **ones on the diagonal and zeros elsewhere.**

In [19]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random

We can also create arrays with random numbers using Numpy's built-in functions in Random module (`np.random`).

### `rand()`

Create an array of the given shape and populate it with random samples from a uniform distribution over ``[0, 1)``.

In [22]:
# 1-D array with three elements
np.random.rand(3)

array([0.18107496, 0.49748656, 0.78189602])

In [23]:
# row, col
# Note we are not passing a tuple here
np.random.rand(3,2)

array([[0.43449387, 0.53024092],
       [0.07521296, 0.26069295],
       [0.82820292, 0.83758585]])

### `randn()`

Return a sample (or samples) from the "standard normal" or a "Gaussian" distribution. Unlike rand which is uniform.<br>

In [24]:
np.random.randn(2)

array([-1.41576316, -0.06382576])

In [25]:
# No tuple, each dimension as a separate argument
np.random.randn(3,4)

array([[ 0.93293508,  0.29127756,  2.17742814, -0.77568439],
       [-0.12171786,  0.14355374,  0.40322249,  0.38913416],
       [ 0.75449659,  1.01778098,  0.20747371, -0.73646665]])

### `randint()`

Return random integers from `low` (inclusive) to `high` (exclusive).

In [26]:
np.random.randint(1,100)

44

In [27]:
# Returns ten random int
np.random.randint(1,100,10) 

array([18, 57, 59, 64, 89, 24, 85, 82, 32, 78])

## Array Methods & Attributes
Some important Methods and Attributes are important to know:<br>

### Methods:
* reshape()
* max()
* min()
* argmax()
* argmin()
<br>

In [28]:
# lets create 2 arrays using arange() and randint()
array_arange = np.arange(16)
array_ranint = np.random.randint(0,100,10)

In [29]:
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [30]:
array_ranint

array([52, 87, 33,  6, 31, 16, 40, 60, 71, 32])

### `Reshape()`

Returns an array containing the same data with a new shape.

In [56]:
# The product of the two parameters given must equal the size of the orginal array
array_arange.reshape(4, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### `max()` & `min()`

Useful methods for finding max or min values.

In [37]:
array_ranint

array([52, 87, 33,  6, 31, 16, 40, 60, 71, 32])

In [38]:
array_ranint.max()

87

In [39]:
array_ranint.min()

6

### `argmax()` & `argmin()`

Returns index locations of max and min values in array respectively.

In [40]:
array_ranint.argmax()

1

In [41]:
array_ranint.argmin()

3

### Attributes

* `size`
* `shape`
* `dtype` 

In [51]:
# Recall
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [42]:
# Shows the dimenstions of the array
array_arange.shape

(16,)

In [43]:
# Size of the array 
array_arange.size

16

In [44]:
# Type of the data.
array_arange.dtype

dtype('int32')

In [45]:
# Notice the two sets of brackets
array_arange.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [60]:
# The size remains constent
array_arange.reshape(4,4).size

16

In [59]:
array_arange.reshape(4,4).shape

(4, 4)

In [54]:
array_arange.reshape(16,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

In [48]:
array_arange.reshape(16,1).shape

(16, 1)

In [49]:
array_arange.reshape(1,16).shape

(1, 16)